import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="bg-gray-800 text-white p-4 text-center">
          <div className="flex justify-center items-center ">
      <img src="/dinetimelogo.png" width={100} />
          <span className="text-2xl font-bold"> {" "}My Next.js Site</span>
          </div>
          <nav className="mt-1 text-sm">Hey Join and Enjoy !</nav>
        </header>

        <main className="flex-1 p-6">{children}</main>

        <footer className="bg-gray-200 text-center text-black p-4">
          © 2025 My Next.js App — All Rights Reserved
        </footer>
      </body>
    </html>
  );
}
